import Head from 'next/head'
import Image from 'next/image'
import HomePage from './components/HomePage'

// Import css files
import "slick-carousel/slick/slick.css";
import "slick-carousel/slick/slick-theme.css";

export default function Home() {
  return (
    <>
      <Head>
        <title>Attack On Titan for fans</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
     
      
        <HomePage />
   
    
    
      </main>
    </>
  )
}
